// Generate the sibling `page.actions.ts` file when none exists.
// Once a file exists at the target path, the user owns it — we never
// overwrite, so they can freely edit the Bindings type and action bodies.

export type ActionsStubInput = {
  actionsUsed: string[];
  bindingsUsed: string[];
};

export function generateActionsStub(input: ActionsStubInput): string {
  const bindingsBlock =
    input.bindingsUsed.length > 0
      ? input.bindingsUsed.map((name) => `  ${name}: unknown;`).join("\n")
      : "  // Add typed bindings here as you reference them in your .md.";

  const actionsBlock =
    input.actionsUsed.length > 0
      ? input.actionsUsed
          .map((name) => {
            const wantsForm = looksLikeFormSubmit(name);
            const param = wantsForm ? "_formData: FormData" : "";
            return [
              `export async function ${name}(${param}): Promise<void> {`,
              "  // TODO: implement",
              "}",
            ].join("\n");
          })
          .join("\n\n")
      : "// No actions referenced in your .md yet.";

  return [
    "// Generated by markdown-computer on first compile.",
    "// You own this file — edit freely. The compiler will not overwrite it.",
    "",
    "export type Bindings = {",
    bindingsBlock,
    "};",
    "",
    actionsBlock,
    "",
  ].join("\n");
}

// Heuristic: actions wired up via `@form submit="..."` get a FormData arg,
// plain `action="..."` button handlers do not. We can't tell from the action
// name alone, so we use a name-based hint: anything starting with "save",
// "submit", "create", or "update" is treated as form-style.
function looksLikeFormSubmit(name: string): boolean {
  return /^(save|submit|create|update|register|signin|signup|signUp)/i.test(
    name
  );
}
