import type { PageNode } from "../ast/types";
import type { Registry } from "../registry/types";
import { type CodegenContext, createContext } from "./context";
import { indent } from "./jsx";
import { renderBlocks } from "./render-block";

export type GenerateOptions = {
  registry: Registry;
  componentName: string;
  // Module specifier the generated file uses to import actions/bindings.
  // Defaults to a sibling `./page.actions` import.
  actionsModulePath?: string;
};

export type GenerateResult = {
  tsx: string;
  // Names referenced in the source — surfaced so the CLI can build a stub
  // page.actions.ts and (eventually) JIT-install missing shadcn components.
  actionsUsed: string[];
  bindingsUsed: string[];
  shadcnComponents: string[];
};

export function generate(
  page: PageNode,
  opts: GenerateOptions
): GenerateResult {
  const ctx = createContext({
    registry: opts.registry,
    componentName: opts.componentName,
    actionsModulePath: opts.actionsModulePath ?? "./page.actions",
  });

  const body = renderBlocks(page.children, ctx, 3);
  const titleHeading = page.title
    ? `${indent(3)}<h1 className="text-3xl font-semibold">${page.title}</h1>\n`
    : "";

  const importBlock = renderImports(ctx);
  const tsx = [
    "// AUTO-GENERATED by markdown-computer — do not edit by hand.\n",
    importBlock,
    "\n",
    `export default function ${ctx.componentName}(bindings: Bindings) {\n`,
    `${indent(1)}return (\n`,
    `${indent(2)}<main className="flex flex-col gap-8">\n`,
    titleHeading,
    body,
    body.length > 0 ? "\n" : "",
    `${indent(2)}</main>\n`,
    `${indent(1)});\n`,
    "}\n",
  ].join("");

  return {
    tsx,
    actionsUsed: [...ctx.actionsUsed].sort(),
    bindingsUsed: [...ctx.bindingsUsed].sort(),
    shadcnComponents: [...ctx.shadcnComponents].sort(),
  };
}

function renderImports(ctx: CodegenContext): string {
  const lines: string[] = [];
  // shadcn / project component imports, sorted by module path
  const sortedModules = [...ctx.imports.entries()].sort((a, b) =>
    a[0] < b[0] ? -1 : 1
  );
  for (const [from, named] of sortedModules) {
    const list = [...named].sort().join(", ");
    lines.push(`import { ${list} } from "${from}";`);
  }
  // Always import actions namespace + Bindings type.
  lines.push(`import * as actions from "${ctx.actionsModulePath}";`);
  lines.push(`import type { Bindings } from "${ctx.actionsModulePath}";`);
  return lines.join("\n");
}
